### ISSUE TITLE
how to improt this app

### ISSUE THREAD

**Issue by stupidxian** [HeartSaVioR/spark-sql-kafka-offset-committer#1]
Hello, I'm a beginner，
I want to ask how to import this program
I didn't find this in Maven

**Comment by HeartSaVioR** [comment]
Thanks for showing interest on the project!
I haven't setup the publish mechanism on the artifact - for now it requires build on your own and add the artifact jar file as `--files`. I'll setup publishing the artifact soon.

**Comment by HeartSaVioR** [comment]
Just released. 

```
<dependency>
  <groupId>net.heartsavior.spark</groupId>
  <artifactId>spark-sql-kafka-offset-committer</artifactId>
  <version>0.1.0</version>
</dependency>
```

It could be up to 48hrs to search and/or download the artifact. Please wait for up to 2 days and let me know if it doesn't work afterwards. Thanks!

**Comment by stupidxian** [comment]
thank you，i got it.
