### ISSUE TITLE
Can sparkstreaming use this assembly

### ISSUE THREAD

**Issue by stupidxian** [HeartSaVioR/spark-sql-kafka-offset-committer#2]
I use “spark-streaming-kafka-0-10_2.12” to read from kafka.
It seems that it can only used by Structured Streaming.
Can sparkstreaming use this assembly? It doesn't matter if it's not possible, I'll take some time to change my code using Structured Streaming.

![image](https://user-images.githubusercontent.com/35219069/69114654-f2b26e80-0ac0-11ea-8de9-ada6cd6a7cc6.png)

![image](https://user-images.githubusercontent.com/35219069/69114586-d0205580-0ac0-11ea-9266-e5eedebd698a.png)

**Comment by HeartSaVioR** [comment]
Sorry it doesn't support DStream; that's why I add "spark-sql" in the project name. Please convert your code to Structured Streaming. Thanks!
