### ISSUE TITLE
Spark to read last committed offsets

### ISSUE THREAD

**Issue by kishansdpt** [HeartSaVioR/spark-sql-kafka-offset-committer#3]
Hi ,
We tried with your approach  and able to commit the offsets manually  with command "**kafkaConsumer.commitSync()**"  .  But when we try to read last committed offset through spark structured stream    **.option("startingOffsets","earliest");**   it is not picking latest committed offsets .

At present we are using another kafka consumer to get last commited offsets of all partition of specific topic's by passing same groupId and passing those offsets to sprark  like   **option("startingOffsets", "{\"topicName\":{\"0\":2764}}")**   to read the data . and its working as expected .

please let us know is there any way to get last committed offsets through spark structured stream.

**Comment by HeartSaVioR** [comment]
Hi.

This product is not meant to change how structured streaming manages offsets. It deals with its own checkpoint system "intentionally", and this product doesn't help there.

Hope this helps.
