### ISSUE TITLE
NullPointerException is thrown in KafkaOffsetCommitterListener

### ISSUE THREAD

**Issue by szvasas** [HeartSaVioR/spark-sql-kafka-offset-committer#9]
When StreamingQuery is started but there are no new messages to process, [this](https://github.com/HeartSaVioR/spark-sql-kafka-offset-committer/blob/develop-spark3.0/src/main/scala/net/heartsavior/spark/KafkaOffsetCommitterListener.scala#L49) line throws a NullpointerException.

The reason is that lastExecution is null so exec will be Some(null).

The exception is thrown continuously until at least one message is processed.

**Comment by HeartSaVioR** [comment]
Nice finding! Would you mind submitting the fix? Otherwise I'll go fixing it. Thanks for reporting!

**Comment by szvasas** [comment]
Sure, I will submit a PR soon.
